// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kyve/stakers/v1beta1/stakers.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StakerStatus ...
type StakerStatus int32

const (
	// STAKER_STATUS_UNSPECIFIED ...
	STAKER_STATUS_UNSPECIFIED StakerStatus = 0
	// STAKER_STATUS_ACTIVE ...
	STAKER_STATUS_ACTIVE StakerStatus = 1
	// STAKER_STATUS_INACTIVE ...
	STAKER_STATUS_INACTIVE StakerStatus = 2
)

var StakerStatus_name = map[int32]string{
	0: "STAKER_STATUS_UNSPECIFIED",
	1: "STAKER_STATUS_ACTIVE",
	2: "STAKER_STATUS_INACTIVE",
}

var StakerStatus_value = map[string]int32{
	"STAKER_STATUS_UNSPECIFIED": 0,
	"STAKER_STATUS_ACTIVE":      1,
	"STAKER_STATUS_INACTIVE":    2,
}

func (x StakerStatus) String() string {
	return proto.EnumName(StakerStatus_name, int32(x))
}

func (StakerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d209d1a2a74d375d, []int{0}
}

// Staker ...
type Staker struct {
	// pool_id ...
	PoolId uint64 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// staker ...
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// amount ...
	Amount uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// unbonding_amount ...
	UnbondingAmount uint64 `protobuf:"varint,4,opt,name=unbonding_amount,json=unbondingAmount,proto3" json:"unbonding_amount,omitempty"`
	// commission ...
	Commission string `protobuf:"bytes,5,opt,name=commission,proto3" json:"commission,omitempty"`
	// moniker ...
	Moniker string `protobuf:"bytes,6,opt,name=moniker,proto3" json:"moniker,omitempty"`
	// website ...
	Website string `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	// logo
	Logo string `protobuf:"bytes,8,opt,name=logo,proto3" json:"logo,omitempty"`
	// points // TODO should points be in bundles
	Points uint64 `protobuf:"varint,9,opt,name=points,proto3" json:"points,omitempty"`
	// status
	Status StakerStatus `protobuf:"varint,10,opt,name=status,proto3,enum=kyve.stakers.v1beta1.StakerStatus" json:"status,omitempty"`
}

func (m *Staker) Reset()         { *m = Staker{} }
func (m *Staker) String() string { return proto.CompactTextString(m) }
func (*Staker) ProtoMessage()    {}
func (*Staker) Descriptor() ([]byte, []int) {
	return fileDescriptor_d209d1a2a74d375d, []int{0}
}
func (m *Staker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Staker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Staker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Staker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staker.Merge(m, src)
}
func (m *Staker) XXX_Size() int {
	return m.Size()
}
func (m *Staker) XXX_DiscardUnknown() {
	xxx_messageInfo_Staker.DiscardUnknown(m)
}

var xxx_messageInfo_Staker proto.InternalMessageInfo

func (m *Staker) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *Staker) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Staker) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Staker) GetUnbondingAmount() uint64 {
	if m != nil {
		return m.UnbondingAmount
	}
	return 0
}

func (m *Staker) GetCommission() string {
	if m != nil {
		return m.Commission
	}
	return ""
}

func (m *Staker) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *Staker) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Staker) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Staker) GetPoints() uint64 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *Staker) GetStatus() StakerStatus {
	if m != nil {
		return m.Status
	}
	return STAKER_STATUS_UNSPECIFIED
}

// UnbondingStakingEntry
// Creates an entry for an upcoming unbonding of a staker which is put in the unbonding fifo queue and
// executed after the unbonding time is over.
type UnbondingStakingQueueEntry struct {
	// index is a monotonically increasing integer to order the entries
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// staker ...
	Staker string `protobuf:"bytes,2,opt,name=staker,proto3" json:"staker,omitempty"`
	// pool_id ...
	PoolId uint64 `protobuf:"varint,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// amount ...
	Amount uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// creation_time ...
	CreationTime uint64 `protobuf:"varint,5,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
}

func (m *UnbondingStakingQueueEntry) Reset()         { *m = UnbondingStakingQueueEntry{} }
func (m *UnbondingStakingQueueEntry) String() string { return proto.CompactTextString(m) }
func (*UnbondingStakingQueueEntry) ProtoMessage()    {}
func (*UnbondingStakingQueueEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d209d1a2a74d375d, []int{1}
}
func (m *UnbondingStakingQueueEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingStakingQueueEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingStakingQueueEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingStakingQueueEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingStakingQueueEntry.Merge(m, src)
}
func (m *UnbondingStakingQueueEntry) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingStakingQueueEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingStakingQueueEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingStakingQueueEntry proto.InternalMessageInfo

func (m *UnbondingStakingQueueEntry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *UnbondingStakingQueueEntry) GetStaker() string {
	if m != nil {
		return m.Staker
	}
	return ""
}

func (m *UnbondingStakingQueueEntry) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *UnbondingStakingQueueEntry) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UnbondingStakingQueueEntry) GetCreationTime() uint64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

// UnbondingState stores the state for the unbonding of stakes and delegations.
type UnbondingStakingQueueState struct {
	// low_index ...
	LowIndex uint64 `protobuf:"varint,1,opt,name=low_index,json=lowIndex,proto3" json:"low_index,omitempty"`
	// high_index ...
	HighIndex uint64 `protobuf:"varint,2,opt,name=high_index,json=highIndex,proto3" json:"high_index,omitempty"`
}

func (m *UnbondingStakingQueueState) Reset()         { *m = UnbondingStakingQueueState{} }
func (m *UnbondingStakingQueueState) String() string { return proto.CompactTextString(m) }
func (*UnbondingStakingQueueState) ProtoMessage()    {}
func (*UnbondingStakingQueueState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d209d1a2a74d375d, []int{2}
}
func (m *UnbondingStakingQueueState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingStakingQueueState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingStakingQueueState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingStakingQueueState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingStakingQueueState.Merge(m, src)
}
func (m *UnbondingStakingQueueState) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingStakingQueueState) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingStakingQueueState.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingStakingQueueState proto.InternalMessageInfo

func (m *UnbondingStakingQueueState) GetLowIndex() uint64 {
	if m != nil {
		return m.LowIndex
	}
	return 0
}

func (m *UnbondingStakingQueueState) GetHighIndex() uint64 {
	if m != nil {
		return m.HighIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("kyve.stakers.v1beta1.StakerStatus", StakerStatus_name, StakerStatus_value)
	proto.RegisterType((*Staker)(nil), "kyve.stakers.v1beta1.Staker")
	proto.RegisterType((*UnbondingStakingQueueEntry)(nil), "kyve.stakers.v1beta1.UnbondingStakingQueueEntry")
	proto.RegisterType((*UnbondingStakingQueueState)(nil), "kyve.stakers.v1beta1.UnbondingStakingQueueState")
}

func init() {
	proto.RegisterFile("kyve/stakers/v1beta1/stakers.proto", fileDescriptor_d209d1a2a74d375d)
}

var fileDescriptor_d209d1a2a74d375d = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x6e, 0xd3, 0x30,
	0x1c, 0xc7, 0x9b, 0x2e, 0xcb, 0xd6, 0x9f, 0x06, 0x54, 0x56, 0x35, 0x4c, 0xd1, 0xa2, 0xaa, 0x5c,
	0x0a, 0x42, 0x8d, 0x06, 0x37, 0x6e, 0x65, 0x64, 0x52, 0x34, 0xa9, 0x82, 0xa6, 0x9d, 0x80, 0x4b,
	0x94, 0xa4, 0x56, 0x6a, 0xb5, 0xb1, 0xab, 0xc4, 0x59, 0xd7, 0x37, 0xe0, 0xc8, 0x23, 0x20, 0xf1,
	0x16, 0x3c, 0x01, 0xc7, 0x1d, 0x39, 0xa2, 0xf6, 0x45, 0x90, 0x1d, 0x67, 0xb4, 0x12, 0xdc, 0xfc,
	0xfd, 0x63, 0xfb, 0xe7, 0x8f, 0x12, 0xe8, 0xce, 0xd7, 0x37, 0xc4, 0xc9, 0x45, 0x38, 0x27, 0x59,
	0xee, 0xdc, 0x9c, 0x47, 0x44, 0x84, 0xe7, 0x95, 0xee, 0x2f, 0x33, 0x2e, 0x38, 0x6a, 0xc9, 0x4e,
	0xbf, 0xf2, 0x74, 0xa7, 0xdd, 0x4a, 0x78, 0xc2, 0x55, 0xc1, 0x91, 0xab, 0xb2, 0xdb, 0xfd, 0x51,
	0x07, 0xcb, 0x57, 0x4d, 0xf4, 0x18, 0x8e, 0x96, 0x9c, 0x2f, 0x02, 0x3a, 0xc5, 0x46, 0xc7, 0xe8,
	0x99, 0x23, 0x4b, 0x4a, 0x6f, 0x8a, 0x30, 0x1c, 0x85, 0x71, 0xcc, 0x0b, 0x26, 0x70, 0xbd, 0x63,
	0xf4, 0x1a, 0xa3, 0x4a, 0xa2, 0x53, 0xb0, 0xc2, 0x54, 0x05, 0x07, 0xe5, 0x8e, 0x52, 0xa1, 0xe7,
	0xd0, 0x2c, 0x58, 0xc4, 0xd9, 0x94, 0xb2, 0x24, 0xd0, 0x0d, 0x53, 0x35, 0x1e, 0xdd, 0xfb, 0x83,
	0xb2, 0x6a, 0x03, 0xc4, 0x3c, 0x4d, 0x69, 0x9e, 0x53, 0xce, 0xf0, 0xa1, 0x3a, 0x7f, 0xc7, 0x91,
	0x97, 0xa7, 0x9c, 0xd1, 0x39, 0xc9, 0xb0, 0x55, 0x5e, 0xae, 0xa5, 0x4c, 0x56, 0x24, 0xca, 0xa9,
	0x20, 0xf8, 0xa8, 0x4c, 0xb4, 0x44, 0x08, 0xcc, 0x05, 0x4f, 0x38, 0x3e, 0x56, 0xb6, 0x5a, 0xcb,
	0x51, 0x97, 0x9c, 0x32, 0x91, 0xe3, 0x46, 0xf5, 0x38, 0xa9, 0xd0, 0x1b, 0xb0, 0x72, 0x11, 0x8a,
	0x22, 0xc7, 0xd0, 0x31, 0x7a, 0x0f, 0x5f, 0x75, 0xfb, 0xff, 0xa2, 0xd7, 0x2f, 0x19, 0xf9, 0xaa,
	0x39, 0xd2, 0x3b, 0xba, 0xdf, 0x0c, 0x68, 0x4f, 0xaa, 0xf7, 0xc8, 0x06, 0x65, 0xc9, 0x87, 0x82,
	0x14, 0xc4, 0x65, 0x22, 0x5b, 0xa3, 0x16, 0x1c, 0x52, 0x36, 0x25, 0xb7, 0x1a, 0x67, 0x29, 0xe4,
	0x20, 0xe5, 0xe1, 0x1a, 0xa6, 0x56, 0xbb, 0xf8, 0x0f, 0xf6, 0xf0, 0xff, 0x85, 0x6c, 0xee, 0x41,
	0x7e, 0x06, 0x0f, 0xe2, 0x8c, 0x84, 0x82, 0x72, 0x16, 0x08, 0x9a, 0x12, 0x05, 0xcf, 0x1c, 0x9d,
	0x54, 0xe6, 0x98, 0xa6, 0xa4, 0xfb, 0xf1, 0x3f, 0x13, 0xca, 0x97, 0x10, 0xf4, 0x14, 0x1a, 0x0b,
	0xbe, 0x0a, 0x76, 0xa7, 0x3c, 0x5e, 0xf0, 0x95, 0xa7, 0x06, 0x3d, 0x03, 0x98, 0xd1, 0x64, 0xa6,
	0xd3, 0xba, 0x4a, 0x1b, 0xd2, 0x51, 0xf1, 0x0b, 0x0a, 0x27, 0xbb, 0x50, 0xd0, 0x19, 0x3c, 0xf1,
	0xc7, 0x83, 0x2b, 0x77, 0x14, 0xf8, 0xe3, 0xc1, 0x78, 0xe2, 0x07, 0x93, 0xa1, 0xff, 0xde, 0xbd,
	0xf0, 0x2e, 0x3d, 0xf7, 0x5d, 0xb3, 0x86, 0x30, 0xb4, 0xf6, 0xe3, 0xc1, 0xc5, 0xd8, 0xbb, 0x76,
	0x9b, 0x06, 0x6a, 0xc3, 0xe9, 0x7e, 0xe2, 0x0d, 0x75, 0x56, 0x6f, 0x9b, 0x5f, 0xbe, 0xdb, 0xb5,
	0xb7, 0x97, 0x3f, 0x37, 0xb6, 0x71, 0xb7, 0xb1, 0x8d, 0xdf, 0x1b, 0xdb, 0xf8, 0xba, 0xb5, 0x6b,
	0x77, 0x5b, 0xbb, 0xf6, 0x6b, 0x6b, 0xd7, 0x3e, 0xbf, 0x4c, 0xa8, 0x98, 0x15, 0x51, 0x3f, 0xe6,
	0xa9, 0x73, 0xf5, 0xe9, 0xda, 0x1d, 0x12, 0xb1, 0xe2, 0xd9, 0xdc, 0x89, 0x67, 0x21, 0x65, 0xce,
	0xed, 0xfd, 0x8f, 0x22, 0xd6, 0x4b, 0x92, 0x47, 0x96, 0xfa, 0xe6, 0x5f, 0xff, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xcc, 0x96, 0x11, 0x8b, 0x45, 0x03, 0x00, 0x00,
}

func (m *Staker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Staker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Staker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x50
	}
	if m.Points != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.Points))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Logo) > 0 {
		i -= len(m.Logo)
		copy(dAtA[i:], m.Logo)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Logo)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Website) > 0 {
		i -= len(m.Website)
		copy(dAtA[i:], m.Website)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Website)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Commission) > 0 {
		i -= len(m.Commission)
		copy(dAtA[i:], m.Commission)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Commission)))
		i--
		dAtA[i] = 0x2a
	}
	if m.UnbondingAmount != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.UnbondingAmount))
		i--
		dAtA[i] = 0x20
	}
	if m.Amount != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x12
	}
	if m.PoolId != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UnbondingStakingQueueEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingStakingQueueEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingStakingQueueEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreationTime != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.CreationTime))
		i--
		dAtA[i] = 0x28
	}
	if m.Amount != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x20
	}
	if m.PoolId != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Staker) > 0 {
		i -= len(m.Staker)
		copy(dAtA[i:], m.Staker)
		i = encodeVarintStakers(dAtA, i, uint64(len(m.Staker)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UnbondingStakingQueueState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingStakingQueueState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingStakingQueueState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HighIndex != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.HighIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.LowIndex != 0 {
		i = encodeVarintStakers(dAtA, i, uint64(m.LowIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStakers(dAtA []byte, offset int, v uint64) int {
	offset -= sovStakers(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Staker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovStakers(uint64(m.PoolId))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovStakers(uint64(m.Amount))
	}
	if m.UnbondingAmount != 0 {
		n += 1 + sovStakers(uint64(m.UnbondingAmount))
	}
	l = len(m.Commission)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	l = len(m.Website)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	l = len(m.Logo)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	if m.Points != 0 {
		n += 1 + sovStakers(uint64(m.Points))
	}
	if m.Status != 0 {
		n += 1 + sovStakers(uint64(m.Status))
	}
	return n
}

func (m *UnbondingStakingQueueEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovStakers(uint64(m.Index))
	}
	l = len(m.Staker)
	if l > 0 {
		n += 1 + l + sovStakers(uint64(l))
	}
	if m.PoolId != 0 {
		n += 1 + sovStakers(uint64(m.PoolId))
	}
	if m.Amount != 0 {
		n += 1 + sovStakers(uint64(m.Amount))
	}
	if m.CreationTime != 0 {
		n += 1 + sovStakers(uint64(m.CreationTime))
	}
	return n
}

func (m *UnbondingStakingQueueState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LowIndex != 0 {
		n += 1 + sovStakers(uint64(m.LowIndex))
	}
	if m.HighIndex != 0 {
		n += 1 + sovStakers(uint64(m.HighIndex))
	}
	return n
}

func sovStakers(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStakers(x uint64) (n int) {
	return sovStakers(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Staker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Staker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Staker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingAmount", wireType)
			}
			m.UnbondingAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commission = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Website", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Website = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Logo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Points", wireType)
			}
			m.Points = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Points |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= StakerStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingStakingQueueEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingStakingQueueEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingStakingQueueEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Staker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakers
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakers
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Staker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTime", wireType)
			}
			m.CreationTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingStakingQueueState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingStakingQueueState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingStakingQueueState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowIndex", wireType)
			}
			m.LowIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LowIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighIndex", wireType)
			}
			m.HighIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HighIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStakers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStakers(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStakers
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStakers
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStakers
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStakers
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStakers        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStakers          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStakers = fmt.Errorf("proto: unexpected end of group")
)
